### ISSUE TITLE
Login via SSO - LDAP / AD

### ISSUE THREAD

**Issue by diemello** [CMCuritiba/portal-volto#18]
Estudar o uso de plugin do Plone, para uso do SSO,LDAP ou AD.

**Comment by acpj21** [comment]
O @brunosoli sugeriu a criação de um docker-compose com as seguintes configurações:
default.conf
/
´upstream backend {
  server backend:8080;
}
upstream frontend {
  server frontend:3000;
}

server {
  listen 80  default_server;
  server_name  localhost;

  location ~ /\+\+api\+\+($|/.*) {
      rewrite ^/(\+\+api\+\+\/?)+($|/.*) /VirtualHostBase/http/$server_name/Plone/++api++/VirtualHostRoot/$2 break;
      proxy_pass http://backend;
  }

  location ~ / {
      location ~* \.(js|jsx|css|less|swf|eot|ttf|otf|woff|woff2)$ {
          add_header Cache-Control "public";
          expires +1y;
          proxy_pass http://frontend;
      }
      location ~* static.*\.(ico|jpg|jpeg|png|gif|svg)$ {
          add_header Cache-Control "public";
          expires +1y;
          proxy_pass http://frontend;
      }

      proxy_set_header        Host $host;
      proxy_set_header        X-Real-IP $remote_addr;
      proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header        X-Forwarded-Proto $scheme;
      proxy_redirect http:// https://;
      proxy_pass http://frontend;
  }
}´
/

docker-comppose.yml
´
´version: "3"
# https://6.dev-docs.plone.org/install/containers/examples/nginx-volto-plone.html
services:

  webserver:
    image: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    ports:
    - "80:80"

  frontend:
    image: plone/plone-frontend:latest
    environment:
      RAZZLE_INTERNAL_API_PATH: http://backend:8080/Plone
    ports:
    - "3000:3000"
    depends_on:
      - backend

  backend:
    image: plone/plone-backend:6.0
    environment:
      SITE: Plone
      # https://6.docs.plone.org/install/containers/images/backend.html
      ADDONS: "pas.plugins.ldap"
    volumes:
      - data:/data
    ports:
    - "8080:8080"

volumes:
  data: {}

**Comment by brunosoli** [comment]
A sugestão é apenas para provisionar um ambiente de teste funcional com autenticação LDAP.
A melhor forma de provisionar/instalar o portal em ambiente produtivo ainda precisa ser estudada.

Qual é a ideia dessa issue?
Vocês estão pesquisando o formato de instalação do portal?

**Comment by acpj21** [comment]
--> Vocês estão pesquisando o formato de instalação do portal?
Exato. Estamos estudando as formas de login dos usuários para não necessitar cadastrar/descadastrar os usuários manualmente, na nova instalação.

Estamos moldando o formato do produto e este é um dos itens que fazem parte dos requisitos.
Em um momento futuro, será necessária uma reunião contigo, para o delineamento de como acomodar o novo site na AWS.

**Comment by brunosoli** [comment]
Acho que cês tão fazendo o nosso trabalho hahaha
@CMCuritiba/div-de-arquitetura

**Comment by acpj21** [comment]
hahahaha.... por isso comentei de uma conversa de sincronização....

**Comment by acpj21** [comment]
Em testes preliminares, testei o addon collective.saml2 em um docker (usado o exemplo dos arquivos acima). O frontend e o backend não subiram por algum motivo, que não consegui entender neste momento.

**Comment by acpj21** [comment]
Complementando: somente com o addon collective.saml2, o backend não "sobe", apesar de não gerar erros...

**Comment by brunosoli** [comment]
https://github.com/collective/collective.saml2/issues/7

Não é compatível com Python 3, talvez seja melhor usar o [dm.zope.saml2](https://pypi.org/project/dm.zope.saml2/) mesmo.

**Comment by ramiroluz** [comment]
A parte do Plone com LDAP deu certo. Se der certo o SAML2 podemos fechar essa issue eu acredito.

https://user-images.githubusercontent.com/293174/235240841-aa69808c-4d48-407e-809a-4dc11ea3a880.webm

**Comment by acpj21** [comment]
![Image](https://user-images.githubusercontent.com/13138784/236849820-b6774f77-0632-48e8-99d7-d130ac6e22eb.png)

Está instalado no meu local. Estou lendo a documentação para efetuar a configuração.

**Comment by acpj21** [comment]
Por problemas na instalação da interface do o dm.zope.saml2 (dm.zope.schema), optei por usar o [pas.plugins.oic](https://github.com/collective/pas.plugins.oidc/). Após a instalação já foi possível ver a tela de cadastro das informações do sistema de autenticação, anexada abaixo:


![Image](https://github.com/CMCuritiba/portal-volto/assets/13138784/51cab4c5-a58d-4560-ae81-518e0032b587)

**Comment by acpj21** [comment]
Para ficar documentado, o pacote dm.zope.saml2, foi instalado no local através do pip e foi "registrado" no Plone 6 (no meu local) nos arquivos requirements.txt, constraints.txt e mx.ini. Sendo que neste último, foi especificado o uso da versão 5.0.1. Sendo esta a última versão lançada (conferida no dia 12/05/2023). 
No momento que era feito o make build-backend e make build-frontend nenhum erro de importação ocorria.
A documentação do pacote apontava para procurar as configurações no link http://localhost:8080/Plone/acl_users (máquina local).

**Comment by acpj21** [comment]
Instalação plugin pas.plugins.oidc:
No arquivo backend/src/nome_site/setup.py, item install_requires: Colocar o termo "pas.plugins.oidc", na primeira posição.
