### ISSUE TITLE
Configurar SSO de teste para Portal Plone.

### ISSUE THREAD

**Issue by ramiroluz** [CMCuritiba/portal-volto#29]
A configuração do KeyCloack deve levar em conta as seguintes urls.

Root URL: http://localhost/api/
Home URL: http://localhost/api/
Valid redirect URIs: http://localhost/api/acl_users/oidc/callback

**Comment by ramiroluz** [comment]
https://github.com/CMCuritiba/portal-volto/issues/30

**Comment by ramiroluz** [comment]
A configuração que funcionou para **redirect_url** foi `http://localhost:8081/Plone*`

 O logout funciona se habilitar no keycloak a opção `--spi-login-protocol-openid-connect-legacy-logout-redirect-uri=true`

Existe uma proposta de correção para o plugin que não precisaria habilitar a opção acima. https://github.com/collective/pas.plugins.oidc/issues/27

**Comment by acpj21** [comment]
Configuração atual do KeyCloack:
Root URL: http://localhost:8080/Plone/
Home URL: http://localhost:8080/Plone/
Valid redirect URIs: http://localhost:8080/Plone*
