### ISSUE TITLE
Investigar atalho para refresh do cache de hospedagem.

### ISSUE THREAD

**Issue by ramiroluz** [CMCuritiba/portal-volto#39]
Com um certo intervalo de tempo, a página inicial do [Portal da CMC](https://www.curitiba.pr.leg.br/) não é atualizada, mesmo tendo informações novas cadastradas. Aparenta ser um problema de cache do sistema.

**Comment by acpj21** [comment]
Nas configurações do site, conforme imagem abaixo, há uma opção de "Configuração de Cache", denominada de cacheamento.


![Image](https://github.com/CMCuritiba/portal-volto/assets/13138784/aa14e095-726f-4a8c-af03-a4aadda823fd)

Foram alteradas várias configurações, porém elas não surtiram efeito imediato.

**Comment by acpj21** [comment]
Ao procurar dados sobre a issue [[Investigar gerenciador de FAQ.](https://github.com/CMCuritiba/portal-volto/issues/37)](https://github.com/CMCuritiba/portal-volto/issues/37), achei um comentário sobre lentidão do Plne/Zope no FreeBSD. O título da página é [FREEBSD + ZOPE/PLONE, UMA IDÉIA FRUSTRANTE?](https://www.vivaolinux.com.br/artigo/FreeBSD-+-Zope-Plone-uma-ideia-frustrante).

**Comment by acpj21** [comment]
Pesquisando os addons instalados no portal, achei o [collective.cover 1.0a9](https://pypi.org/project/collective.cover/1.0a9/). No tópico CMFContentPanels, há o seguinte texto:
"Code is very old, but still maintained (at least works in Plone 4). Allows to create complex layouts TTW and use any layout as a template. Easy to extend and edit (but is terrible to find a content to use). Needs a lot of memory to work and aggressive cache settings."
Se for essa a questão, há um arquivo no  [docker do portal](https://github.com/CMCuritiba/portalmodelo/blob/master/buildout.d/use-zeo.cfg) que tem algumas configurações de cache. Quando eu acesso a parte de configuração do site, não tenho acesso a estas congiurações.
Pergunto: compensa alterar as configurações de cache, contidas no arquivo mencionado, e enviar as alterações pra o Interlegis?

**Comment by ramiroluz** [comment]
Confirmando novas informações. O cache em questão é um sistema compartilhado. Não é viável criar um botão para que cada Câmara Municipal possa reiniciar.
